linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintln
      - fmt.Fprintf
      - (strings.Builder).Write
      - (strings.Builder).WriteByte
      - (strings.Builder).WriteString
